version: '3'

volumes:
  db:
    driver: local

services:
  mariadb:
    image: mariadb:10.4.12-bionic
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=ugr
      - MYSQL_USER=ugr
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db:/var/lib/mysql
  bot:
    build:
      context: .
    container_name: bot
    restart: unless-stopped
    depends_on:
      - mariadb
    environment:
      - TOKEN
      - SENTRY_DSN
      - LOG_CHANNEL_ID
      - DEBUG
      - USERNAME
      - DB_DRIVER=mysql
      - DB_DSN=ugr:${MYSQL_PASSWORD}@tcp(mariadb:3306)/ugr?charset=utf8mb4&parseTime=true&loc=${TZ}
  adminer:
    image: adminer
    container_name: adminer
    restart: unless-stopped
    ports:
      - 45677:8080
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb

